/***********************************************************************/
/*                                                                     */
/*  FILE        :GPTcontrol.c                                          */
/*  DATE        :Sat, Mar 10, 2012                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX62T                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.51).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
                  


//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif
#include "iodefine_RPDL.h"
#include "HIT_common.h"
#include "HIT_highimp.h"
#include "HIT_make_angle.h"
#include "HIT_current_pi.h"


#include	<machine.h>
#include	<_h_c_lib.h>
//#include	<stddef.h>					// Remove the comment when you use errno
//#include 	<stdlib.h>					// Remove the comment when you use rand()
#include	"typedefine.h"		// Define Types
#include	"stacksct.h"		// Stack Sizes (Interrupt and User)
extern int psw_value;
unsigned char HIT_iic_word_send[2] ;/////// address and data to iic send


#include<math.h>
#include <mathf.h>
void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	PORTA.DDR.BIT.B4=1;
	PORTA.DDR.BIT.B5=1;
	PORT2.DDR.BIT.B2 = 1;
	
//  MTU set	
	MTU1.TMDR.BIT.MD = 0X08;
	MTU1.TCR.BIT.CCLR = 0X01;
	MTU1.TIOR.BYTE = 0X0F;
	MTU1.TGRA = 0X00;
	MTU1.TGRB = 0X00;
	
	
	HIT_hardwaresetup();/*hardware-initial*/
	
/////////////////////////////////////////////////////////iic set/////////////////////////////////////////////////
	SYSTEM.MSTPCRB.BIT.MSTPB21 = 0;
	PORTB.DDR.BIT.B1 = 0;
	PORTB.DDR.BIT.B2 = 0;
	PORTB.ICR.BIT.B1 = 1;
	PORTB.ICR.BIT.B2 = 1;

	RIIC0.ICCR1.BIT.ICE = 0;//unable iic
	
	RIIC0.ICMR3.BIT.SMBS = 0;//IIC MODE
	RIIC0.ICMR1.BIT.CKS = 0X03;//DIV 8 CLOCK
	RIIC0.ICMR2.BIT.TMOL = 0;//PDL_IIC_TIMEOUT_DISABLE
	RIIC0.ICMR2.BIT.TMOH = 0;
	RIIC0.ICMR2.BIT.SDDL = 0X00;//PDL_IIC_SDA_DELAY_0
	RIIC0.ICMR3.BIT.NF = 0X00;//PDL_IIC_NF_DISABLE
	RIIC0.ICFER.BIT.NALE = 0;//PDL_IIC_NTALD_DISABLE
	RIIC0.ICFER.BIT.SALE = 0;//PDL_IIC_SALD_DISABLE
	RIIC0.ICSER.BIT.SAR0E = 0;//PDL_IIC_SLAVE_0_DISABLE
	RIIC0.ICSER.BIT.SAR1E = 0;
	RIIC0.ICSER.BIT.SAR2E = 0;
	RIIC0.ICSER.BIT.GCAE = 0;//PDL_IIC_SLAVE_GCA_DISABLE
	RIIC0.ICSER.BIT.DIDE = 0;//PDL_IIC_DEVICE_ID_DISABLE
	RIIC0.ICSER.BIT.HOAE = 0;//PDL_IIC_HOST_ADDRESS_DISABLE
	
	RIIC0.ICBRL.BIT.BRL = 23;//Transfer rate control ( 1 << 31 ) | ( 23 << 8 ) | 23
	RIIC0.ICBRH.BIT.BRH = 23;
	
	RIIC0.ICCR1.BIT.ICE = 1;//unable iic	
	HIT_iic_word_send[0] = 2;/////the address iic send
	HIT_iic_word_send[1] = 8;////the data iic send
///////////////////////////////////////////////////////////////iic set END///////////////////////////////////////////////		
	
	
	HIT_par_initial();/*parermetre calculate*/

	R_PG_SCI_Set_C2();
	R_PG_SCI_StartReceiving_C2(&rcvbuff_char,8);
//	FLASH.DFLRE0.WORD = 0X2D03;
	FLASH.DFLRE0.WORD = 0X2DFF;
	FLASH.DFLRE1.WORD = 0XD2FF;
	HIT_iocontrol();/*io control*/


//	PORTE.DDR.BIT.B2=1;
	while(1)
	{
		;		
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
