#ifndef HITIOCONTROLC
#define HITIOCONTROLC
#include "iodefine.h"
void HIT_iocontrol()
{
	PORT9.DDR.BIT.B6=1;
//	PORT2.DDR.BIT.B4 = 1;//CUIN
//	PORT9.DDR.BIT.B2 = 1;//ALM 
//	PORT9.DR.BIT.B2 = 1;//ALM 
//	PORT9.DDR.BIT.B1 = 1;//S_RDY 

	PORT9.DR.BIT.B6=0;

//	PORT9.DR.BIT.B2 = 1;//ALM_output 
//	PORTA.DDR.BIT.B3 = 1;//RL_ON	
//	PORTA.DDR.BIT.B2 = 1;//RG_ON
	PORT1.DDR.BIT.B1=1;
//	PORT1.DDR.BIT.B0 = 0;//S_ON
//	PORT1.ICR.BIT.B0 = 1;
//	PORT1.DDR.BIT.B1 = 0;//N_CL
//	PORT1.ICR.BIT.B1 = 1;
//	PORT9.DDR.BIT.B4 = 0;//P_CL
//	PORT9.ICR.BIT.B4 = 1;
}

#endif