/***********************************************************************/
/*                                                                     */
/*  FILE        :GPTcontrol.c                                          */
/*  DATE        :Sat, Mar 10, 2012                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX62T                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.51).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
                  


//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif
#include "iodefine_RPDL.h"
#include "HIT_common.h"
#include "HIT_highimp.h"
#include "HIT_make_angle.h"
#include "HIT_current_pi.h"
#include"math.h"
#include"mathf.h"



#include	<machine.h>
#include	<_h_c_lib.h>
//#include	<stddef.h>					// Remove the comment when you use errno
//#include 	<stdlib.h>					// Remove the comment when you use rand()
#include	"typedefine.h"		// Define Types
#include	"stacksct.h"		// Stack Sizes (Interrupt and User)
extern int psw_value;
unsigned char HIT_iic_word_send[2] ;/////// address and data to iic send


#include<math.h>
#include <mathf.h>
void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif
int start=0;
int chushihua=0;
int chushihua_time;
extern unsigned char HIT_pwm_mode_choose;
extern float HIT_alarm ;

void main(void)
{	
	PORT7.DDR.BIT.B0 = 1;//modify 20131130
	PORT7.DDR.BIT.B1 = 1;
	PORT7.DDR.BIT.B2 = 1;
	PORT7.DDR.BIT.B3 = 1;
	PORT7.DDR.BIT.B4 = 1;
	PORT7.DDR.BIT.B5 = 1;
	PORT7.DDR.BIT.B6 = 1;
	        PORT7.DR.BIT.B0 = 0;//add20141222
			PORT7.DR.BIT.B1 = 0;
			PORT7.DR.BIT.B2 = 0;
			PORT7.DR.BIT.B3 = 0;
			PORT7.DR.BIT.B4 = 0;
			PORT7.DR.BIT.B5 = 0;
			PORT7.DR.BIT.B6 = 0;
	PORTA.DDR.BIT.B4=1;
	PORTA.DDR.BIT.B5=0;
	PORT2.DDR.BIT.B2 = 1;
	PORT2.DDR.BIT.B3 = 1;
	PORT2.DR.BIT.B3 = 0;
	PORTA.DDR.BIT.B3=1;//20150709
		PORT9.DDR.BIT.B5 = 1;
		PORT9.DR.BIT.B5 = 1;
	    PORTA.DR.BIT.B3=1;//20150709
	PORT3.DDR.BIT.B1=1;
	/////////////////////////////////////////////////////////iic set/////////////////////////////////////////////////
/*	SYSTEM.MSTPCRB.BIT.MSTPB21 = 0;
	PORTB.DDR.BIT.B1 = 0;
	PORTB.DDR.BIT.B2 = 0;
	PORTB.ICR.BIT.B1 = 1;
	PORTB.ICR.BIT.B2 = 1;

	RIIC0.ICCR1.BIT.ICE = 0;//unable iic
	
	RIIC0.ICMR3.BIT.SMBS = 0;//IIC MODE
	RIIC0.ICMR1.BIT.CKS = 0X03;//DIV 8 CLOCK
	RIIC0.ICMR2.BIT.TMOL = 0;//PDL_IIC_TIMEOUT_DISABLE
	RIIC0.ICMR2.BIT.TMOH = 0;
	RIIC0.ICMR2.BIT.SDDL = 0X00;//PDL_IIC_SDA_DELAY_0
	RIIC0.ICMR3.BIT.NF = 0X00;//PDL_IIC_NF_DISABLE
	RIIC0.ICFER.BIT.NALE = 0;//PDL_IIC_NTALD_DISABLE
	RIIC0.ICFER.BIT.SALE = 0;//PDL_IIC_SALD_DISABLE
	RIIC0.ICSER.BIT.SAR0E = 0;//PDL_IIC_SLAVE_0_DISABLE
	RIIC0.ICSER.BIT.SAR1E = 0;
	RIIC0.ICSER.BIT.SAR2E = 0;
	RIIC0.ICSER.BIT.GCAE = 0;//PDL_IIC_SLAVE_GCA_DISABLE
	RIIC0.ICSER.BIT.DIDE = 0;//PDL_IIC_DEVICE_ID_DISABLE
	RIIC0.ICSER.BIT.HOAE = 0;//PDL_IIC_HOST_ADDRESS_DISABLE
	
	RIIC0.ICBRL.BIT.BRL = 23;//Transfer rate control ( 1 << 31 ) | ( 23 << 8 ) | 23
	RIIC0.ICBRH.BIT.BRH = 23;
	
	RIIC0.ICCR1.BIT.ICE = 1;//unable iic	
	HIT_iic_word_send[0] = 2;/////the address iic send
	HIT_iic_word_send[1] = 8;////the data iic send*/
///////////////////////////////////////////////////////////////iic set END///////////////////////////////////////////////
////////////////////////////////////////////////////////////sci1 set//////////////////////////////////////////
	SYSTEM.MSTPCRB.BIT.MSTPB30 = 0;	//SCI1
//	SYSTEM.MSTPCRB.BIT.MSTPB29 = 0;	//SCI2
	
	SCI1.SMR.BIT.CKS = 0;
	SCI1.BRR = 9;
	
	SCI1.SMR.BIT.CM = 1;//PDL_SCI_SYNC 
	SCI1.SCR.BIT.TE = 1;//PDL_SCI_TX_CONNECTED 
	SCI1.SCR.BIT.RE = 0;//PDL_SCI_RX_CONNECTED 
	SCI1.SCR.BIT.CKE = 0X00;//PDL_SCI_CLK_INT_OUT	
	
	SCI1.SCR.BIT.TE = 1;
//////////////////////////////////////////////////////////////////////////////////


//	R_PG_SCI_Set_C0();


////////////////////////////////////////////////////////////sci1 set END//////////////////////////////////////	
//////////////////////////////////////////////////////////////spi set/////////////////////////////////////////////
	SYSTEM.MSTPCRA.BIT.MSTPA28 = 1;//STOP DTC/////分体型
	SYSTEM.MSTPCRB.BIT.MSTPB17 = 0;//ENABLE SPI
	RSPI0.SPCR.BIT.SPMS = 1;//3 XIAN MOSHI
	
	RSPI0.SPCR.BIT.MSTR = 0;//PDL_SCI_MODE_SYNC_MASTER
	
	RSPI0.SPCR.BIT.TXMD = 0;//PDL_SPI_TRANSMIT_ONLY
	
	IOPORT.PFHSPI.BIT.RSPIS = 0;//PDL_SPI_PIN_A
	IOPORT.PFGSPI.BIT.RSPCKE = 1;//PDL_SPI_PIN_RSPCK_ENABLE
	IOPORT.PFGSPI.BIT.MISOE = 1;
	IOPORT.PFGSPI.BIT.MOSIE = 1;
	PORT2.DDR.BIT.B3 = 0;
	PORT2.ICR.BIT.B3 = 1;
	PORT2.DDR.BIT.B4 = 0;
	PORT2.ICR.BIT.B4 = 1;
	
	RSPI0.SPPCR.BIT.MOIFE = 0;//PDL_SPI_PIN_MOSI_IDLE_LAST
	
	RSPI0.SPDCR.BIT.SPLW = 1;//PDL_SPI_BUFFER_128
	
	RSPI0.SPSCR.BIT.SPSLN = 0;//PDL_SPI_FRAME_1_1
	
	RSPI0.SPCKD.BIT.SCKDL = 0;//1 个RSPCK
	
	RSPI0.SSLND.BIT.SLNDL = 0;//PDL_SPI_SSL_DELAY_1
	
	RSPI0.SPND.BIT.SPNDL = 0;//PDL_SPI_NEXT_DELAY_1
	
	RSPI0.SPCMD0.BIT.BRDV = 0;//
	RSPI0.SPBR = 0X13;//1M
	
	
	
	//////////////////////////////////
	RSPI0.SPSCR.BIT.SPSLN = 0;
	
	RSPI0.SPCMD0.BIT.CPHA = 1;//PDL_SPI_CLOCK_MODE_0
	RSPI0.SPCMD0.BIT.CPOL = 0;
	
	RSPI0.SPCMD0.BIT.BRDV = 0;//PDL_SPI_DIV_1
	
	RSPI0.SPCMD0.BIT.SPB = 0XFF;//4;//PDL_SPI_LENGTH_16
	RSPI0.SPCMD0.BIT.LSBF = 0;//PDL_SPI_MSB_FIRST
	
	RSPI0.SPCR.BIT.SPE = 1;
	
//////////////////////////////////////////////////////////////spi set end//////////////////////////////////////////	

	HIT_par_initial();/*parermetre calculate*/
	
/*	for(chushihua_time=0;chushihua_time<20000000;chushihua_time++)
	{
		chushihua_time = chushihua_time;	
		//	HIT_pwm_af = 0;
		//	HIT_pwm_bf = 0;
		//	HIT_pwm_cf = 0;
	}
	chushihua=0;*/
	
	HIT_hardwaresetup();/*hardware-initial*/
	HIT_ready_go = 1;
	HIT_pwm_mode_choose = 1;
//	HIT_alarm = 1;
	
/*
	if(HIT_run_mode == 3)
	{
	//  MTU set	
	//  MTU1 phase count set	
		SYSTEM.MSTPCRA.BIT.MSTPA9 = 0;
		MTU1.TMDR.BIT.MD = 0X04;
		MTU1.TCR.BIT.CCLR = 0X01;
		MTU1.TIOR.BIT.IOA = 0X09;
		MTU1.TIOR.BIT.IOB = 0X08;
		MTU1.TGRA = 0X00;
		MTU1.TGRB = 0X00;
		IOPORT.PFCMTU.BIT.TCLKS	= 0X00;
		PORT3.ICR.BIT.B2 = 1;
		PORT3.ICR.BIT.B3 = 1;
		PORTA.ICR.BIT.B5 = 1;	
		MTU.TSTRA.BIT.CST1 = 1;
	//  MTU set	end		
	}*/
	R_PG_SCI_Set_C2();
	R_PG_SCI_StartReceiving_C2(&rcvbuff_char,8);
//	FLASH.DFLRE0.WORD = 0X2D03;
	FLASH.DFLRE0.WORD = 0X2DFF;
	FLASH.DFLRE1.WORD = 0XD2FF;
	HIT_iocontrol();/*io control*/


	while(1)
	{
/*		if(start==1)
		{
		HIT_shouchaoqi_con_servon();
	//	HIT_shouchaoqi_con_servon();	
		start=0;
		}
		if(chushihua==1)
		{
			for(chushihua_time=0;chushihua_time<6000;chushihua_time++)
			{
				HIT_par_write_to_ee();	
			}
			chushihua=0;	
		}
		;	*/	
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
